import { ArrowUpRight, Mail } from 'lucide-react'
import { ContactComposer } from '@/components/contact/ContactComposer'

export default function ContactPage() {
  return <main>
    <section className="hero-paper border-b border-line py-20 md:py-28"><div className="site-container grid gap-12 md:grid-cols-[1fr_.7fr] md:items-end"><div><p className="eyebrow">Kontak / Ravatech</p><h1 className="page-title mt-5">Mulai saja dari <span className="editorial-serif text-accent">ceritanya.</span></h1></div><p className="lead">Tulis beberapa kalimat tentang hal yang ingin kamu buat atau perbaiki. Kita bisa mencari langkah berikutnya dari sana.</p></div></section>
    <section className="site-container grid gap-10 py-16 lg:grid-cols-[.7fr_1.3fr] lg:py-24"><div><p className="eyebrow">Hubungi Ravatech</p><h2 className="section-title mt-4">Pilih cara yang paling mudah.</h2><a href="mailto:contact@ravatech.com" className="group mt-8 flex items-start gap-5 border-t border-b border-line py-6 transition-colors hover:text-accent"><span className="grid h-12 w-12 shrink-0 place-items-center bg-[#eac5ad] text-accent"><Mail size={22}/></span><span className="min-w-0"><span className="block text-xs font-bold uppercase tracking-widest text-muted">Email</span><span className="mt-2 block break-all font-semibold">contact@ravatech.com</span><span className="mt-2 inline-flex items-center gap-1 text-sm font-bold text-accent">Tulis langsung <ArrowUpRight size={15}/></span></span></a><p className="mt-6 max-w-sm text-sm leading-7 text-muted">Belum punya spesifikasi lengkap? Tidak apa-apa. Cukup ceritakan konteks dan bagian yang terasa sulit sekarang.</p></div><ContactComposer/></section>
    <section className="border-t border-line bg-white py-16 md:py-20"><div className="site-container"><p className="eyebrow">Setelah kamu menghubungi</p><div className="mt-8 grid gap-5 border-t border-line md:grid-cols-3">{[['01','Kamu bercerita','Kirim beberapa kalimat tentang kebutuhanmu.'],['02','Kami mempelajari','Masalah dan batasan yang kamu bagikan ditinjau lebih dulu.'],['03','Tentukan langkah','Jika cocok, kita berdiskusi tentang lingkup dan arah.']].map(([number,title,description]) => <article key={number} className="border-b border-line py-7 md:pr-8"><span className="eyebrow">{number}</span><h2 className="mt-8 font-heading text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-7 text-muted">{description}</p></article>)}</div></div></section>
  </main>
}
